version: 0.0
os: linux
files:
  - source:  /
    destination: /var/www/html/rescue-pat/

hooks:
  AfterInstall:
    - location: ./devops/hooks/after-install.sh
      runas: ec2-user
#  ApplicationStart:
#    - location: ./devops/hooks/application_start.sh
#      runas: ec2-user

